openapi: 3.0.0
info:
  description: From the todo list tutorial on goswagger.io
  title: A Todo list application
  version: 1.0.0
paths:
  /:
    get:
      tags:
        - todos
      operationId: find_todos
      parameters:
        - name: since
          in: query
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        200:
          description: list the todo ope
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      tags:
        - todos
      operationId: addOne
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/item"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    put:
      tags:
        - todos
      operationId: updateOne
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/item"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      tags:
        - todos
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    item:
      type: object
      required:
        - description
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        description:
          type: string
          minLength: 1
        completed:
          type: boolean
    error:
      type: object
      required:
        - message
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
