/*
 * A Todo list application
 *
 * From the todo list tutorial on goswagger.io
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
