/*
 * A Todo list application
 *
 * From the todo list tutorial on goswagger.io
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/kappa-lab/openapi-generator-playground/server/go"
)

func main() {
	log.Printf("Server started")

	TodosApiService := openapi.NewTodosApiService()
	TodosApiController := openapi.NewTodosApiController(TodosApiService)

	router := openapi.NewRouter(TodosApiController)

	log.Fatal(http.ListenAndServe(":3333", router))
}
